const assert = require("node:assert/strict");
require("../color-utils.js");
const colors = global.OledNightColors;
assert.deepEqual(colors.parseColor("rgba(255, 0, 12, 0.5)"), { r: 255, g: 0, b: 12, a: 0.5 });
assert.equal(colors.mapBackground(colors.parseColor("rgb(255,255,255)"), "oled"), "#000000");
assert.equal(colors.mapBackground(colors.parseColor("rgba(0,0,0,0)"), "oled"), null);
assert.match(colors.mapBackground(colors.parseColor("rgb(0,120,255)"), "oled"), /^hsl\(.*var\(--oln-strength/);
assert.equal(colors.mapForeground(colors.parseColor("rgb(15,15,15)")), "hsl(0 0% var(--oln-light, 88%))");
assert.equal(colors.mapForeground(colors.parseColor("rgb(240,240,240)")), "hsl(0 0% var(--oln-light, 88%))");
assert.match(colors.mapForeground(colors.parseColor("rgb(0,90,200)")), /calc\(var\(--oln-light, 88%\) \* 0\.86\)/);
assert.match(colors.mapBackground(colors.parseColor("rgb(80,80,80)"), "oled"), /var\(--oln-strength/);
assert.equal(colors.mapBorder(colors.parseColor("rgb(40,40,40)")), "rgb(255 255 255 / calc(12% + 18% * var(--oln-strength, 0.72)))");
assert.equal(colors.isProtectedMediaTag("shreddit-player"), true);
assert.equal(colors.isProtectedMediaTag("example-gallery-carousel"), true);
assert.equal(colors.isProtectedMediaTag("div"), false);
assert.equal(colors.usesNativeSafeMode("youtube.com"), true);
assert.equal(colors.usesNativeSafeMode("www.youtube.com"), true);
assert.equal(colors.usesNativeSafeMode("music.youtube.com"), true);
assert.equal(colors.usesNativeSafeMode("notyoutube.com"), false);
assert.equal(colors.usesNativeSafeMode("reddit.com"), false);
console.log("color-utils: 17 assertions passed");
const cachedColor = colors.parseColor('rgb(12, 34, 56)');
assert.ok(Object.isFrozen(cachedColor));
assert.strictEqual(colors.parseColor('rgb(12, 34, 56)'), cachedColor);
const mutableColor = {r:0,g:0,b:0,a:1};
const darkLuminance = colors.luminance(mutableColor);
mutableColor.r=mutableColor.g=mutableColor.b=255;
assert.ok(colors.luminance(mutableColor)>darkLuminance);
for(let i=0;i<600;i++) colors.parseColor(`rgba(12,34,56,${i/600})`);
assert.deepEqual(colors.parseColor('rgb(12, 34, 56)'),cachedColor);
assert.equal(colors.parseColor('invalid'),null);
console.log('Color cache preserves correctness after eviction and mutable inputs');

assert.equal(colors.siteProfile('www.amazon.com'), 'amazon');
assert.equal(colors.siteProfile('amazon.com.evil.example'), '');
